project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include ("core.urls")),
    path("escuela/", include ("escuela.urls")),
]

project/core/urls.py
from django.urls import path
from core.views import index

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
]

project/escuela/urls.py
from django.urls import path
from escuela.views import index, listar_alumnos, crear_alumno

app_name = "escuela"

urlpatterns = [
    path("", index, name="index"),
    path("escuela/listar_alumnos", listar_alumnos, name="listar_alumnos"),
    path("escuela/crear_alumno", crear_alumno, name="crear_alumno"),
]

project/core/models.py
from django.db import models

# Create your models here.

project/escuela/models.py
from django.db import models

class Materia(models.Model):
    nombre = models.CharField(max_length=150, unique=True)
    codigo = models.CharField(max_length=30, unique=True)
    
    def __str__(self) -> str:
        return self.nombre
    
class Docente(models.Model):
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    materia_id = models.ForeignKey(Materia, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self) -> str:
        return f"{self.apellido}, {self.nombre}"


class Alumno(models.Model):
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    docente_id = models.ForeignKey(Docente, on_delete=models.SET_NULL, null=True)
    materia_id = models.ForeignKey(Materia, on_delete=models.SET_NULL, null=True)
    
    def __str__(self) -> str:
        return f"{self.apellido}, {self.nombre}"
    
    

project/escuela/forms.py
from django import forms
from . import models

class AlumnoForm(forms.ModelForm):
    class Meta:
        model = models.Alumno
        fields = ["nombre", "apellido", "fecha_de_nacimiento", "docente_id", "materia_id"]

project/core/views.py
from django.shortcuts import render

def index(request):
    return render (request, "core/index.html")

# Create your views here.

project/escuela/views.py
from django.shortcuts import render, redirect
from escuela.models import Alumno
from escuela.forms import AlumnoForm

def index(request):
    return render (request, "escuela/index.html")

def listar_alumnos(request):
    consulta = Alumno.objects.all()
    contexto = {"Alumnos":consulta}
    return render(request, "escuela/listar_alumnos.html", contexto)

def crear_alumno(request):
    if request.method == "POST":
        form = AlumnoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("escuela:listar_alumnos")
    else:
        form = AlumnoForm()
    return render(request, "escuela/crear_alumno.html",{"form":form})

    

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
                
            {% endblock title %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'core/components/navbar.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'core/components/footer.html' %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/components/footer.html
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4"><p class="m-0 text-center text-white">Elaborado por el equipo de la Escuela en 2024</p></div>
        </footer>

project/core/templates/core/components/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container px-4">
        <a class="navbar-brand" href="#page-top">Sistema de registro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'escuela:index' %}">Alumnos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'escuela:index' %}">Docentes</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'escuela:index' %}">Materia</a></li>
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Escuela Las Brusquitas
{% endblock title %}

{% block content %}


    <!-- Header-->
    <header class="bg-primary bg-gradient text-white">
        <div class="container px-4 text-center">
            <h1 class="fw-bolder">Bienvenidos a la pagina de la Escuela Las Brusquitas</h1>
            <p class="lead">Podras consultar las notas de tus materias</p>
    </header>
    <!-- About section-->
    
    <!-- Bootstrap core JS-->

{% endblock content %}

project/escuela/templates/escuela/crear_alumno.html
{% extends 'core/base.html' %}

{% block title %}
    <h2>Agregar alumno/a</h2>
{% endblock title %}

{% block content %}
    <h1>Colegio Las Brusquitas</h1>
    <h2>Agregar alumno/a</h2>

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
            <button type="submit">Agregar</button>
    </form>

    
{% endblock content %}

project/escuela/templates/escuela/index.html
{% extends 'core/base.html' %}

{% block title %}
    Sistema de Gestion 
{% endblock title %}

{% block content %}

    <h1>Escuela Las Brusquitas</h1>
    <div><a href="{% url 'escuela:listar_alumnos' %}">Lista de Alunos</a></div>
    <div><a href="{% url 'escuela:crear_alumno' %}">Agregar alumno/a</a></div>
    
{% endblock content %}

project/escuela/templates/escuela/listar_alumnos.html
{% extends 'core/base.html' %}

{% block title %}
    <h2>Listado de alumnos</h2>
{% endblock title %}

{% block content %}
    <h1>Colegio Las Brusquitas</h1>
    <h2>Listado de alumnos</h2>

    {% for alumno in Alumnos %}
        <p>Nombre: {{alumno.nombre}}</p>
        <p>Apellido: {{alumno.apellido}}</p>
        <p>Fecha de nacimiento: {{alumno.fecha_de_nacimiento}}</p>
        <p>Materia: {{alumno.materia_id}}</p>
        <p>docente: {{alumno.docente_id}}</p>
    {% endfor %}
{% endblock content %}